# This is a basic workflow to help you get started with Actions

name: test

# Controls when the action will run. Triggers the workflow on push or pull
# request events for the specified branches.
on:
  push:
    branches: [ feature/* , master, fix/*, hotfix/*, release/* ]

# Ensure redundant parallel runs don't occur in the same workflow.
# Use either PR or branch information to prevent such runs.
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

# A workflow run is made up of one or more jobs that can run sequentially or in
# parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    name: pytest
    strategy:
      fail-fast: false
    # A job can run for multiple environments
      matrix:
        python-version: ['3.8', '3.11']
        os: ['ubuntu-latest', 'macos-latest', 'windows-latest']
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}
    concurrency:
      group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}-${{ matrix.os }}-${{ matrix.python-version}}
      cancel-in-progress: true

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Check out
      uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Set up Windows tooling
      if: matrix.os == 'windows-latest'
      uses: crazy-max/ghaction-chocolatey@v3
      with:
        args: install make
    - name: Install dependencies
      run: |
        make install-all
    - name: Run tests
      run: make test-all
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: coverage.xml
        env_vars: OS,PYTHON
        name: codecov-umbrella
        fail_ci_if_error: true
